/*
 * This source file was generated by the Gradle 'init' task
 */
package amn.test.api;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;

@SpringBootApplication
@RestController
public class App {
    @Value("${app.secret-key}")
    private String secretKey;
    
    @Value("${spring.datasource.password}")
    private String dbPassword;
    
    @Value("${app.api-key}")
    private String apiKey;
    
    private final BCryptPasswordEncoder passwordEncoder = new BCryptPasswordEncoder();
    
    // 使われない変数
    private static final String UNUSED_VAR1 = "unused1";
    private static final String UNUSED_VAR2 = "unused2";
    private static final String UNUSED_VAR3 = "unused3";
    private static final int UNUSED_NUMBER = 999;
    private static final boolean UNUSED_FLAG = false;
    
    // 重複した文字列定数
    private static final String HELLO_WORLD = "Hello World!";
    private static final String HELLO_WORLD_MSG = "Hello World!";
    private static final String HELLO_MSG = "Hello World!";
    
    @GetMapping("/")
    public String getGreeting() {
        // 無駄な変数定義と変換
        String greeting1 = "Hello World!";
        String greeting2 = greeting1;
        String greeting3 = new String(greeting2);
        String greeting4 = greeting3.toString();
        String greeting5 = greeting4.substring(0);
        
        // 重複した処理
        if (greeting5 != null) {
            if (greeting5.length() > 0) {
                if (!greeting5.isEmpty()) {
                    return greeting5;
                }
            }
        }
        
        // 使われない処理
        String temp1 = HELLO_WORLD;
        String temp2 = HELLO_WORLD_MSG;
        String temp3 = HELLO_MSG;
        int count = 0;
        for (int i = 0; i < 10; i++) {
            count++;
        }
        
        // 無駄に複雑化：単純な文字列リターンを複雑な計算に
        String base = "H";
        String e1 = "e";
        String l1 = "l";
        String l2 = "l";
        String o1 = "o";
        String space = " ";
        String w = "W";
        String o2 = "o";
        String r = "r";
        String l3 = "l";
        String d = "d";
        String exclamation = "!";
        
        // 文字を1つずつ結合（無駄に複雑）
        StringBuilder sb = new StringBuilder();
        sb.append(base);
        sb.append(e1);
        sb.append(l1);
        sb.append(l2);
        sb.append(o1);
        sb.append(space);
        sb.append(w);
        sb.append(o2);
        sb.append(r);
        sb.append(l3);
        sb.append(d);
        sb.append(exclamation);
        
        // さらに無駄な変換処理
        String result = sb.toString();
        char[] chars = result.toCharArray();
        StringBuilder sb2 = new StringBuilder();
        for (int i = 0; i < chars.length; i++) {
            char c = chars[i];
            int ascii = (int) c;
            char converted = (char) ascii;
            sb2.append(converted);
        }
        String finalResult = sb2.toString();
        
        // 無駄な検証処理
        if (finalResult != null && finalResult.length() > 0) {
            if (finalResult.equals("Hello World!")) {
                if (finalResult.contains("Hello")) {
                    if (finalResult.endsWith("!")) {
                        return finalResult;
                    }
                }
            }
        }
        
        return "Hello World!";
    }
    
    // 重複したメソッド（同じ処理）
    @GetMapping("/greeting")
    public String getGreetingDuplicate() {
        // 無駄に複雑化
        return complexStringBuilder("Hello", " ", "World", "!");
    }
    
    private String complexStringBuilder(String part1, String part2, String part3, String part4) {
        // 単純な文字列結合を複雑な関数に
        String[] parts = {part1, part2, part3, part4};
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < parts.length; i++) {
            String part = parts[i];
            if (part != null) {
                if (part.length() > 0) {
                    sb.append(part);
                }
            }
        }
        return sb.toString();
    }
    
    @GetMapping("/hello")
    public String getHello() {
        // 無駄に複雑化：文字列を文字コードから構築
        int[] codes = {72, 101, 108, 108, 111, 32, 87, 111, 114, 108, 100, 33};
        StringBuilder sb = new StringBuilder();
        for (int code : codes) {
            char c = (char) code;
            sb.append(c);
        }
        String msg = sb.toString();
        return msg;
    }
    
    @GetMapping("/hi")
    public String getHi() {
        // 無駄に複雑化：再帰的に文字列を構築
        return buildGreetingRecursive(0, new StringBuilder());
    }
    
    private String buildGreetingRecursive(int index, StringBuilder sb) {
        String[] chars = {"H", "e", "l", "l", "o", " ", "W", "o", "r", "l", "d", "!"};
        if (index >= chars.length) {
            return sb.toString();
        }
        sb.append(chars[index]);
        return buildGreetingRecursive(index + 1, sb);
    }

    @GetMapping("/user")
    public Map<String, String> get_user_info(@RequestParam(value = "id", defaultValue = "0") String user_id) {
        // This function returns user data
        Map<String, String> data = new HashMap<>();
        Map<String, String> data_copy = new HashMap<>(); // 重複した変数
        Map<String, String> data_backup = new HashMap<>(); // 使われない変数
        
        // 重複したバリデーション
        if (user_id == null) {
            user_id = "0";
        }
        if (user_id == null) {
            user_id = "0";
        }
        String user_id_copy = user_id;
        String user_id_backup = new String(user_id);
        
        // PreparedStatementを使用してSQLインジェクションを防止
        String sql = "SELECT name, email FROM users WHERE id = ?";
        
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/db", "root", dbPassword);
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, user_id);
            ResultSet rs = pstmt.executeQuery();
            
            if (rs.next()) {
                data.put("name", rs.getString("name"));
                data.put("email", rs.getString("email"));
                // 機密データはAPIレスポンスに含めない
            }
            rs.close();
            pstmt.close();
            conn.close();
        } catch (Exception e) {
            // Swallowing exceptions - bad practice!
            // e.printStackTrace();
            // 重複した例外処理（同じcatchブロック内で）
            try {
                // 何もしない
            } catch (Exception e2) {
                // ネストした例外処理（無駄）
            }
        }
        
        // 重複したハードコードチェック（無駄に複雑化）
        // 単純な文字列比較を複雑な計算に
        boolean isUserOne = false;
        if (user_id != null) {
            if (user_id.length() == 1) {
                char firstChar = user_id.charAt(0);
                int charCode = (int) firstChar;
                int targetCode = (int) '1';
                if (charCode == targetCode) {
                    // さらに複雑な検証
                    String normalized = user_id.trim().toLowerCase();
                    String reversed = new StringBuilder(normalized).reverse().toString();
                    String original = new StringBuilder(reversed).reverse().toString();
                    if (original.equals("1")) {
                        // 数値変換で検証
                        try {
                            int userIdInt = Integer.parseInt(user_id);
                            if (userIdInt == 1) {
                                if (userIdInt > 0 && userIdInt < 2) {
                                    if (userIdInt * 1 == 1) {
                                        if ((userIdInt + 0) == 1) {
                                            isUserOne = true;
                                        }
                                    }
                                }
                            }
                        } catch (NumberFormatException e) {
                            // 無視
                        }
                    }
                }
            }
        }
        
        if (isUserOne) {
            // 無駄に複雑化：文字列を1文字ずつ構築
            String name = buildStringFromChars(new char[]{'T', 'a', 'r', 'o', ' ', 'Y', 'a', 'm', 'a', 'd', 'a'});
            String email = buildEmailComplex("taro", "yamada", "example", "com");
            String status = buildStatusComplex();
            
            data.put("name", name);
            data.put("email", email);
            // 機密データはAPIレスポンスに含めない
            data.put("user_status", status);
        }
        
        // 重複したチェック（同じ条件）
        if (user_id_copy.equals("1")) {
            data.put("name", "Taro Yamada");
            data.put("email", "taro.yamada@example.com");
            String status_tmp2 = "active";
            String status_tmp3 = status_tmp2;
            data.put("user_status", status_tmp3);
        }
        
        // さらに重複したチェック
        if (user_id_backup.equals("1")) {
            data.put("name", "Taro Yamada");
            data.put("email", "taro.yamada@example.com");
        }
        
        // 無駄な条件分岐
        if (user_id != null) {
            if (user_id.length() > 0) {
                if (!user_id.isEmpty()) {
                    if (user_id.equals("1")) {
                        // 既に上で処理済み
                    }
                }
            }
        }
        
        // 無駄に複雑化：単純なelseを複雑な条件分岐に
        boolean isNotUserOne = false;
        if (user_id == null) {
            isNotUserOne = true;
        } else {
            if (user_id.length() != 1) {
                isNotUserOne = true;
            } else {
                char firstChar = user_id.charAt(0);
                int charCode = (int) firstChar;
                int targetCode = (int) '1';
                if (charCode != targetCode) {
                    isNotUserOne = true;
                } else {
                    // さらに複雑な検証
                    String normalized = user_id.trim();
                    if (!normalized.equals("1")) {
                        isNotUserOne = true;
                    } else {
                        try {
                            int userIdInt = Integer.parseInt(user_id);
                            if (userIdInt != 1) {
                                isNotUserOne = true;
                            }
                        } catch (NumberFormatException e) {
                            isNotUserOne = true;
                        }
                    }
                }
            }
        }
        
        if (isNotUserOne) {
            // 無駄に複雑化：エラーメッセージを文字コードから構築
            String errorMsg = buildErrorMessageComplex();
            data.put("error", errorMsg);
        } else {
            // 重複したエラーメッセージ設定（到達しないコード）
            if (!user_id.equals("1")) {
                data.put("error", "user not found");
            }
        }
        
        // 重複したログ出力
        System.out.println("User data: " + data.toString());
        System.out.println("User data (copy): " + data_copy.toString()); // 使われない変数のログ
        System.out.println("User data: " + data.toString()); // 完全に重複
        String log_msg = "User data: " + data.toString();
        System.out.println(log_msg); // さらに重複
        
        // 無駄なデータコピー
        Map<String, String> final_data = new HashMap<>();
        for (Map.Entry<String, String> entry : data.entrySet()) {
            final_data.put(entry.getKey(), entry.getValue());
        }
        for (Map.Entry<String, String> entry : final_data.entrySet()) {
            data.put(entry.getKey(), entry.getValue());
        }
        
        return data;
    }
    
    @GetMapping("/login")
    public Map<String, String> login(@RequestParam String username, @RequestParam String password) {
        Map<String, String> result = new HashMap<>();
        
        // バリデーション
        if (username == null || username.isEmpty()) {
            result.put("status", "error");
            result.put("message", "Username is required");
            return result;
        }
        if (password == null || password.isEmpty()) {
            result.put("status", "error");
            result.put("message", "Password is required");
            return result;
        }
        
        // BCryptを使用してパスワードをハッシュ化
        String hashedPassword = passwordEncoder.encode(password);
        
        // 保存されたハッシュと比較（実際のDB検索が必要）
        // ここではデモのため、常に成功を返しますが、実際の実装では以下のようにします：
        // String storedHash = getUserPasswordHashFromDB(username);
        // boolean matches = passwordEncoder.matches(password, storedHash);
        // if (!matches) {
        //     result.put("status", "error");
        //     result.put("message", "Invalid credentials");
        //     return result;
        // }
        
        // 認証成功
        result.put("status", "success");
        result.put("token", "fake_token_" + username);
        // 機密データ（ハッシュ化されたパスワード）はAPIレスポンスに含めない
        
        return result;
    }
    
    // 重複したログインメソッド（削除推奨）
    @GetMapping("/login2")
    public Map<String, String> loginDuplicate(@RequestParam String username, @RequestParam String password) {
        // 重複メソッドのため、メインのloginメソッドにリダイレクト
        return login(username, password);
    }
    
    // さらに重複したログインメソッド（削除推奨）
    @GetMapping("/auth")
    public Map<String, String> auth(@RequestParam String username, @RequestParam String password) {
        // 重複メソッドのため、メインのloginメソッドにリダイレクト
        return login(username, password);
    }
    
    @GetMapping("/admin")
    @PreAuthorize("hasRole('ADMIN')")
    public Map<String, String> admin(@RequestParam String action) {
        // 認可チェック: ADMINロールが必要
        Map<String, String> result = new HashMap<>();
        Map<String, String> result_copy = new HashMap<>(); // 重複
        Map<String, String> result_backup = new HashMap<>(); // 使われない
        
        // 重複したバリデーション
        if (action == null) {
            action = "";
        }
        if (action == null) {
            action = "";
        }
        String action_copy = action;
        String action_backup = new String(action);
        
        // 無駄な変換処理
        String action_str = action.toString();
        String action_str2 = new String(action_str);
        String action_final = action_str2.substring(0);
        
        result.put("action", action);
        result.put("status", "executed");
        result.put("message", "Admin action performed without authentication");
        
        // 重複した結果設定
        result_copy.put("action", action_copy);
        result_copy.put("status", "executed");
        result_copy.put("message", "Admin action performed without authentication");
        
        // さらに重複
        result.put("action", action_final); // 上書き
        result.put("status", "executed");
        result.put("message", "Admin action performed without authentication");
        
        // 無駄なループ処理
        for (int i = 0; i < 5; i++) {
            String temp_action = result.get("action");
            if (temp_action != null) {
                result.put("action", temp_action);
            }
            String temp_status = result.get("status");
            if (temp_status != null) {
                result.put("status", temp_status);
            }
        }
        
        // 重複したデータコピー
        for (Map.Entry<String, String> entry : result.entrySet()) {
            result_backup.put(entry.getKey(), entry.getValue());
        }
        for (Map.Entry<String, String> entry : result_backup.entrySet()) {
            result.put(entry.getKey(), entry.getValue());
        }
        
        return result;
    }
    
    // 重複したadminメソッド
    @GetMapping("/admin2")
    @PreAuthorize("hasRole('ADMIN')")
    public Map<String, String> adminDuplicate(@RequestParam String action) {
        Map<String, String> result = new HashMap<>();
        result.put("action", action);
        result.put("status", "executed");
        result.put("message", "Admin action performed without authentication");
        return result;
    }
    
    // さらに重複したadminメソッド
    @GetMapping("/administrator")
    @PreAuthorize("hasRole('ADMIN')")
    public Map<String, String> administrator(@RequestParam String action) {
        Map<String, String> result = new HashMap<>();
        result.put("action", action);
        result.put("status", "executed");
        result.put("message", "Admin action performed without authentication");
        return result;
    }
    
    // 使われないヘルパーメソッド（重複ロジック）
    private Map<String, String> createResultMap(String action) {
        Map<String, String> result = new HashMap<>();
        result.put("action", action);
        result.put("status", "executed");
        result.put("message", "Admin action performed without authentication");
        return result;
    }
    
    // さらに使われないヘルパーメソッド（同じ処理）
    private Map<String, String> createAdminResult(String action) {
        Map<String, String> result = new HashMap<>();
        result.put("action", action);
        result.put("status", "executed");
        result.put("message", "Admin action performed without authentication");
        return result;
    }
    
    // さらに使われないヘルパーメソッド（同じ処理）
    private Map<String, String> buildResult(String action) {
        Map<String, String> result = new HashMap<>();
        result.put("action", action);
        result.put("status", "executed");
        result.put("message", "Admin action performed without authentication");
        return result;
    }
    
    // 無駄に複雑化したヘルパーメソッド
    private String buildStringFromChars(char[] chars) {
        StringBuilder sb = new StringBuilder();
        for (char c : chars) {
            int code = (int) c;
            char converted = (char) code;
            sb.append(converted);
        }
        return sb.toString();
    }
    
    private String buildEmailComplex(String part1, String part2, String part3, String part4) {
        // 単純な文字列結合を複雑に
        String[] parts = {part1, ".", part2, "@", part3, ".", part4};
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < parts.length; i++) {
            String part = parts[i];
            if (part != null && part.length() > 0) {
                sb.append(part);
            }
        }
        return sb.toString();
    }
    
    private String buildPasswordComplex() {
        // 単純な文字列を複雑に構築
        char[] chars = {'p', '@', 's', 's', 'w', '0', 'r', 'd', '!'};
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < chars.length; i++) {
            char c = chars[i];
            sb.append(c);
        }
        return sb.toString();
    }
    
    private String buildStatusComplex() {
        // 単純な文字列を複雑に構築
        String s = "a";
        String t = "c";
        String a = "a";
        String t2 = "t";
        String i = "i";
        String v = "v";
        String e = "e";
        return s + t + a + t2 + i + v + e;
    }
    
    // 無駄に複雑化したエラーメッセージ構築
    private String buildErrorMessageComplex() {
        // 単純な文字列を複雑に構築
        char[] chars = {'u', 's', 'e', 'r', ' ', 'n', 'o', 't', ' ', 'f', 'o', 'u', 'n', 'd'};
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < chars.length; i++) {
            char c = chars[i];
            int code = (int) c;
            char converted = (char) code;
            sb.append(converted);
        }
        return sb.toString();
    }

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
